# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home_slider"
  weight = 1

[[main]]
  name = "About"
  url = "#about"
  weight = 2



[[main]]
  name = "Blog"
  url = "#posts"
  weight = 4


[[main]]
  name = "Why Volcano"
  url = "#required"
  weight = 3

#[[main]]
  #name = "Documentation"
  #url = "docs/"
  #weight = 6


[[main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #000000; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/volcano-sh/"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-x-twitter\" style=\"color: #000000; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/volcano_sh"
  weight = 20

[[main_right]]
  
  name = "<img src=\"/img/icon_slack.svg\" alt=\"slack\" style=\" font-size: 1rem; line-height: 1.25; width:20px; height:20px; margin-top: 9px;\">"
  post = ""
  url = "https://cloud-native.slack.com/archives/C011GJDQS0N"
  weight = 30

# Documentation version latest

[[docs]]
  name = "Home"
  weight = 1
  identifier = "home"

[[docs]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[docs]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[docs]]
  name = "Core Job Management"
  weight = 4
  identifier = "core-job-management"

[[docs]]
  name = "Queue Management"
  weight = 5
  identifier = "queue-management"

[[docs]]
  name = "Scheduling Algorithms & Policies"
  weight = 6
  identifier = "scheduling-algorithms"

[[docs]]
  name = "Resource Management"
  weight = 7
  identifier = "resource-management"

[[docs]]
  name = "Node Management"
  weight = 8
  identifier = "node-management"

[[docs]]
  name = "User Guide"
  weight = 9
  identifier = "user-guide"

[[docs]]
  name = "Key Features"
  weight = 10
  identifier = "features"

[[docs]]
  name = "Ecosystem"
  weight = 11
  identifier = "ecosystem"

[[docs]]
  name = "Scheduler"
  weight = 12
  identifier = "scheduler"

[[docs]]
  name = "CLI"
  weight = 13
  identifier = "cli"

[[docs]]
  name = "Plugins & Extensions"
  weight = 14
  identifier = "plugins"

[[docs]]
  name = "Actions & Operations"
  weight = 15
  identifier = "actions"

[[docs]]
  name = "Multi-Scheduler & Advanced Features"
  weight = 16
  identifier = "advanced"

[[docs]]
  name = "System Features"
  weight = 17
  identifier = "system"

[[docs]]
  name = "Contribution"
  weight = 18
  identifier = "contribution"

# User Guide menu items
[[user-guide]]
  name = "Configure PriorityClass"
  weight = 1
  identifier = "configure-priorityclass"
  url = "/docs/user-guide/how_to_configure_priorityclass_for_job/"

[[user-guide]]
  name = "Configure Scheduler"
  weight = 2
  identifier = "configure-scheduler"
  url = "/docs/user-guide/how_to_configure_scheduler/"

[[user-guide]]
  name = "Use Capacity Plugin"
  weight = 3
  identifier = "use-capacity-plugin"
  url = "/docs/user-guide/how_to_use_capacity_plugin/"

[[user-guide]]
  name = "Use CDP Plugin"
  weight = 4
  identifier = "use-cdp-plugin"
  url = "/docs/user-guide/how_to_use_cdp_plugin/"

[[user-guide]]
  name = "Use ENV Plugin"
  weight = 5
  identifier = "use-env-plugin"
  url = "/docs/user-guide/how_to_use_env_plugin/"

[[user-guide]]
  name = "Use Extender"
  weight = 6
  identifier = "use-extender"
  url = "/docs/user-guide/how_to_use_extender/"

[[user-guide]]
  name = "Use GPU Number"
  weight = 7
  identifier = "use-gpu-number"
  url = "/docs/user-guide/how_to_use_gpu_number/"

[[user-guide]]
  name = "Use GPU Sharing"
  weight = 8
  identifier = "use-gpu-sharing"
  url = "/docs/user-guide/how_to_use_gpu_sharing/"

[[user-guide]]
  name = "Use Job Policy"
  weight = 9
  identifier = "use-job-policy"
  url = "/docs/user-guide/how_to_use_job_policy/"

[[user-guide]]
  name = "Use Job TTL"
  weight = 10
  identifier = "use-job-ttl"
  url = "/docs/user-guide/how_to_use_job_ttl/"

[[user-guide]]
  name = "Use MPI Plugin"
  weight = 11
  identifier = "use-mpi-plugin"
  url = "/docs/user-guide/how_to_use_mpi_plugin/"

[[user-guide]]
  name = "Use NodeGroup Plugin"
  weight = 12
  identifier = "use-nodegroup-plugin"
  url = "/docs/user-guide/how_to_use_nodegroup_plugin/"

[[user-guide]]
  name = "Use NUMA Aware"
  weight = 13
  identifier = "use-numa-aware"
  url = "/docs/user-guide/how_to_use_numa_aware/"

[[user-guide]]
  name = "Use PyTorch Plugin"
  weight = 14
  identifier = "use-pytorch-plugin"
  url = "/docs/user-guide/how_to_use_pytorch_plugin/"

[[user-guide]]
  name = "Use SSH Plugin"
  weight = 15
  identifier = "use-ssh-plugin"
  url = "/docs/user-guide/how_to_use_ssh_plugin/"

[[user-guide]]
  name = "Use Service Plugin"
  weight = 16
  identifier = "use-service-plugin"
  url = "/docs/user-guide/how_to_use_svc_plugin/"

[[user-guide]]
  name = "Use Task Topology Plugin"
  weight = 17
  identifier = "use-task-topology-plugin"
  url = "/docs/user-guide/how_to_use_task_topology_plugin/"

[[user-guide]]
  name = "Use Volcano VGPU"
  weight = 18
  identifier = "use-volcano-vgpu"
  url = "/docs/user-guide/how_to_use_volcano_vgpu/"

# Documentation version v1.11.0

[[v1-11-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-11-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-11-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-11-0]]
  name = "Key Features"
  weight = 4
  identifier = "features"

[[v1-11-0]]
  name = "Ecosystem"
  weight = 5
  identifier = "ecosystem"

[[v1-11-0]]
  name = "Scheduler"
  weight = 6
  identifier = "scheduler"

[[v1-11-0]]
  name = "CLI"
  weight = 7
  identifier = "cli"

[[v1-11-0]]
  name = "Contribution"
  weight = 8
  identifier = "contribution"


# Documentation version v1.10.0

[[v1-10-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-10-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-10-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-10-0]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-10-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-10-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-10-0]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"


# Documentation version v1.9.0

[[v1-9-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-9-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-9-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-9-0]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-9-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-9-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-9-0]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"

# Documentation version v1.8.2

[[v1-8-2]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-8-2]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-8-2]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-8-2]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-8-2]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-8-2]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-8-2]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"

# Documentation version v1.7.0

[[v1-7-0]]
  name = "Home"
  weight = 1
  identifier = "home"

[[v1-7-0]]
  name = "Getting Started"
  weight = 2
  identifier = "getting-started"

[[v1-7-0]]
  name = "Concepts"
  weight = 3
  identifier = "concepts"

[[v1-7-0]]
  name = "Ecosystem"
  weight = 4
  identifier = "ecosystem"

[[v1-7-0]]
  name = "Scheduler"
  weight = 5
  identifier = "scheduler"

[[v1-7-0]]
  name = "CLI"
  weight = 6
  identifier = "cli"

[[v1-7-0]]
  name = "Contribution"
  weight = 7
  identifier = "contribution"

# Blogs

[[posts]]
  name = "Tutorials"
  weight = 5
  identifier = "tutorials"

[[posts]]
  name = "Customers"
  weight = 10
  identifier = "customers"